swagger: '2.0'
info:
  version: 1.0.0
  title: API for VMS Workflow Managment
  description: VMS Workflow Management APIs VMS Workflow Management APIs
basePath: /api/v1
paths:
  /flowTask/tasks:
    get:
      operationId: queryTask
      summary: 查询user task
      tags:
        - Flowtask
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: upload bpmn file  successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  '/flowTask/unclaim/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    post:
      operationId: unclaimTaskByID
      summary: 归还之前认领的task
      tags:
        - Flowtask
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: complete user task successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  /flowTask/complete:
    post:
      operationId: completeTask
      summary: '完成task(e.g. 包含assign,group users)'
      tags:
        - Flowtask
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/CompleteTaskReqVO'
      responses:
        '200':
          description: complete user task successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  /flowTask/claim:
    post:
      operationId: claimTaskByID
      summary: 认领task
      tags:
        - Flowtask
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/ClaimTaskReqVO'
      responses:
        '200':
          description: complete user task successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  '/flowTask/tasks/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    delete:
      operationId: deleteTaskByID
      summary: 根据id删除user task
      tags:
        - Flowtask
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: delete task successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  /processDefinition/deploy:
    get:
      operationId: getProcessDefinitionDeploymentList
      summary: 获取部署列表
      tags:
        - Processdefinition
      produces:
        - application/json
      responses:
        '200':
          description: get deployment list
          schema:
            $ref: '#/definitions/StandardResponse'
  /processDefinition/deploy/upload:
    post:
      operationId: deployProcessDefinitionByUploadZip
      summary: 上传 bpmn zip 文件部署
      tags:
        - Processdefinition
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: bpmnName
          in: query
          required: false
          type: string
        - name: category
          in: query
          required: false
          type: string
        - name: file
          in: formData
          description: The file to upload.
          required: true
          type: file
      responses:
        '200':
          description: upload bpmn file  successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  '/processDefinition/deploy/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: deleteProcessDefinitionById
      summary: 根据deployment ID删除
      tags:
        - Processdefinition
      produces:
        - application/json
      responses:
        '200':
          description: get deployment by id
          schema:
            $ref: '#/definitions/StandardResponse'
    get:
      operationId: getProcessDefinitionById
      summary: 根据deployment ID查询详情
      tags:
        - Processdefinition
      produces:
        - application/json
      responses:
        '200':
          description: get deployment by id
          schema:
            $ref: '#/definitions/StandardResponse'
          examples:
            application/json:
              code: 200
              message: Excepte
              data:
                entityList:
                  - name: alex
                  - name: decimal
  /processDefinition/deploy/predefined:
    post:
      operationId: deployPreDefinedProcessDefinition
      summary: 部署预定义的bpmn文件
      tags:
        - Processdefinition
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: bpmnName
          in: query
          required: true
          type: string
        - name: category
          in: query
          required: false
          type: string
      responses:
        '200':
          description: upload bpmn file  successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  /processInstance:
    post:
      operationId: createProcessInstance
      summary: 创建流程实例
      tags:
        - Processinstance
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/StartProcessInstanceReqVO'
      responses:
        '200':
          description: create instance successfully
          schema:
            $ref: '#/definitions/StandardResponse'
  '/processInstance/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: deleteProcessInstanceByID
      summary: 根据instance id删除流程实例
      tags:
        - Processinstance
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: delete process instance successfully
          schema:
            $ref: '#/definitions/StandardResponse'
    get:
      operationId: queryProcessInstanceByID
      summary: 根据instance id查看流程实例
      tags:
        - Processinstance
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: get process instance list
          schema:
            $ref: '#/definitions/StandardResponse'
  '/processInstance/instanceKey/{key}':
    parameters:
      - name: key
        in: path
        required: true
        type: string
    get:
      operationId: queryProcessInstanceByKey
      summary: 根据instance key获取列表
      tags:
        - Processinstance
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: get process instance list
          schema:
            $ref: '#/definitions/StandardResponse'
  '/processInstance/historic/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: integer
    get:
      operationId: queryTaskHistoricalDataByID
      summary: 根据ID查询 process instance的历史归档记录
      tags:
        - Processinstance
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: get instance historical task list
          schema:
            $ref: '#/definitions/StandardResponse'
parameters:
  'trait:thirdpartyAuthToken:thirdparty_auth_token':
    name: thirdparty_auth_token
    in: header
    required: true
    type: string
definitions:
  DeploymentEntity:
    title: DeploymentEntity
    properties:
      id:
        type: integer
      name:
        type: string
      category:
        type: string
      key:
        type: string
      tenantId:
        type: string
      engineVersion:
        type: string
  StartProcessInstanceReqVO:
    title: StartProcessInstanceReqVO
    properties:
      required:
        - instanceKey
      instanceKey:
        type: string
      applyUserId:
        type: string
      businessKey:
        type: string
      variables:
        type: object
        additionalProperties:
          type: object
  HistroicTaskInstance:
    title: HistroicTaskInstance
    properties:
      deleteReason:
        type: string
      startTime:
        type: string
        format: date-time
      endTime:
        type: string
        format: date-time
      durationInMillis:
        type: integer
        format: int64
      workTimeInMillis:
        type: integer
        format: int64
      claimTime:
        type: string
        format: date-time
  ClaimTaskReqVO:
    title: ClaimTaskReqVO
    required:
      - taskId
      - assignee
    properties:
      taskId:
        type: string
      assignee:
        type: string
  StandardResponse:
    title: StandardResponse
    required:
      - code
      - message
      - data
    properties:
      code:
        type: integer
      message:
        type: string
      data:
        type: object
  CompleteTaskReqVO:
    title: CompleteTaskReqVO
    required:
      - taskId
      - assignee
      - isReviewPass
    properties:
      taskId:
        type: string
      assignee:
        type: string
      isReviewPass:
        type: integer
      returnStart:
        type: integer
      variables:
        type: object
        additionalProperties:
          type: object
  ProcessInstanceEntity:
    title: ProcessInstanceEntity
    properties:
      processDefinitionId:
        type: integer
      processDefinitionName:
        type: string
      processDefinitionKey:
        type: string
      processDefinitionVersion:
        type: integer
      deploymentId:
        type: string
      businessKey:
        type: string
      isSuspended:
        type: boolean
      tenantId:
        type: string
      name:
        type: string
      startUserId:
        type: string
  QueryTaskReqVO:
    title: QueryTaskReqVO
    properties:
      firstResult:
        type: integer
      maxResults:
        type: integer
      assignee:
        type: string
      candidateUser:
        type: string
      candidateGroup:
        type: string